version: 2

references:
  js_deps_cache_key: &js_deps_cache_key v8-dependency-js-deps-{{ checksum "yarn.lock" }}
  js_deps_backup_cache_key: &js_deps_backup_cache_key v8-dependency-js-deps

jobs:
  build:
    docker:
      - image: circleci/node:12.22.0
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
            - *js_deps_cache_key
            - *js_deps_backup_cache_key
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile
      - run:
          name: Eslint
          command: yarn eslint
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
