version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile
      - run:
          name: Eslint
          command: yarn eslint
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
